version: '3.9'

services:
  wowsimpleregistration:
#    image: wowsimpleregistration
    build:
      context: '..'
      dockerfile: './docker/Dockerfile'
    ports:
      - "8080:80"
    environment:
      PAGE_TITLE: "THIS IS A TEST"
      BASEURL: "http://127.0.0.1:8080"
      DEBUG_MODE: 'true'
      CAPTCHA_TYPE: "999"
      DB_AUTH_DBNAME: 'acore_auth'
      DB_AUTH_HOST: 'mariadb'
      DB_AUTH_PORT: '3306'
      DB_AUTH_USER: 'acore'
      DB_AUTH_PASS: 'acore'
      TPL_RULES_1: "Be A Cool Guy"
      TPL_RULES_2: "Also Be A cool GUY"
      REALMLISTS_1_REALMID: '1'
      REALMLISTS_1_REALMNAME: 'Realm 1'
      REALMLISTS_1_DB_HOST: 'mariadb'
      REALMLISTS_1_DB_PORT: '3306'
      REALMLISTS_1_DB_USER: 'acore'
      REALMLISTS_1_DB_PASS: 'acore'
      REALMLISTS_1_DB_NAME: 'acore_characters'

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "wowsimpleregistration"
    volumes:
      - "wowsimpleregistration:/var/lib/mysql"

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: "mariadb"
    ports:
      - "8081:8080"



volumes:
  wowsimpleregistration:
